# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: mgwalker.codes
email: mgwalker@gmail.com
description: My little slice of the web
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mgwalker.codes" # the base hostname & protocol for your site
twitter_username: darkcooger
github_username:  mgwalker

gems: [jekyll-paginate]

# Build settings
markdown: kramdown

paginate: 10
paginate_path: "/:num"
